<form action="<?php echo $this->getUrl("admin/catalog_product/save") ?>" method="post">
    <div class="center">
        <!-- <h1>PHP form</h1> -->
        <div class="form-group row">
            <label for="">SKU : </label>
            <input type="text" placeholder="Enter your product SKU number" name="p_data[sku]" id="">
        </div>
        <br>
        <div class="form-group row">
            <label for="">Product Name : </label>
            <input style="margin-left:10px" type="text" placeholder="Enter your product name" name="p_data[name]" id="">
        </div>
        <br>
        <div class="form-group row">
            <label for="">Color : </label>
            <input type="text" placeholder="Enter your product color" name="p_data[color]" id="">
        </div>
        <br>
        <div class="form-group row">
            <label for="">Size : </label>
            <input type="text" placeholder="Enter your product size" name="p_data[size]" id="">
        </div>
        <br>
        <div class="form-group row">
            <label for="">Description : </label>
            <textarea name="p_data[description]" id="" cols="100" rows="5"></textarea>
        </div>
        <br>
        <div class="form-group row">
            <label for="">Image Link : </label>
            <input type="text" placeholder="Enter product image link" name="p_data[image_link]" id="">
        </div>
        <br>
        <div class="form-group row">
            <label for="">Link : </label>
            <input type="text" placeholder="Enter product link" name="p_data[link]" id="">
        </div>
        <br>
        <div class="category">
            <label for="Category" class="heading">Category :</label>
            <select name="p_data[category_id]" id="categories">
                <option value="1">Bar & Game Room</option>
                <option value="2">BedRoom</option>
                <option value="3">Decor</option>
                <option value="4">Dining & Kitchen</option>
                <option value="5">Lighting</option>
                <option value="6">Living Room</option>
                <option value="7">Mattresses</option>
                <option value="8">Office</option>
                <option value="9">Outdoor</option>
            </select>
        </div>
        <br>
        <div class="form-group-row">
            <label for="">Price : </label>
            <input type="number" placeholder="Enter Price" name="p_data[price]" id="">
        </div>
        <br>
        <div class="form-group-row">
            <label for="">Manufacturer cost : </label>
            <input type="number" placeholder="Manufacurer cost" name="p_data[mfr_cost]" id="">
        </div>
        <br>
        <div class="form-group-row">
            <label for="">Shipping cost : </label>
            <input type="number" placeholder="shipping cost" name="p_data[shipping_cost]" id="">
        </div>
        <br>
        <div class="form-group-row">
            <label for="">Total cost : </label>
            <input type="number" placeholder="Total cost" name="p_data[total_cost]" id="">
        </div>
        <br>
        <div class="form-group-row">
            <label for="">Margin Percentage : </label>
            <input type="number" placeholder="Margin percentage" name="p_data[margin_percentage]" id="">
        </div>
        <br>
        <div class="form-group-row">
            <label for="">Minimum Price : </label>
            <input type="number" placeholder="Minimum price" name="p_data[min_price]" id="">
        </div>
        <br>
        <div class="category">
            <label for="Category" class="heading">Status :</label>
            <select name="p_data[status]" id="categories">
                <option value="0">Enabled</option>
                <option value="1">Disabled</option>
            </select>
        </div>
        <button type="submit" name="submit">Submit</button>

    </div>
    </div>
</form>