<div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->
        <nav class="col-md-3 col-lg-2 d-md-block bg-dark sidebar">
            <div class="sidebar-sticky">
                <h2 class="sidebar-heading">Dashboard</h2>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active dash" href="#">My Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="#">My Wallet</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="<?php echo $this->getUrl('sales/order/list') ?>">My Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="#">Wishlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="<?php echo $this->getUrl('sales/quote/view') ?>">My Cart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash"
                            href="<?php echo $this->getUrl("customer/account/logout") ?>">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <?php
        $customerModel = $this->getCustomer();
        ?>
        <div class="col-md-9 col-lg-10 px-md-4 list">
            <div class="customer-details">
                <h2>Customer Details</h2>
                <div class="customer-info">
                    <h4>Customer Information</h4>
                    <p><strong>Customer Email:</strong>
                        <?php echo $customerModel->getCustomerEmail() ?>
                    </p>
                    <p><strong>Customer Password:</strong>
                        <?php echo $customerModel->getCustomerPassword() ?>
                    </p>
                    <p><strong>First Name:</strong>
                        <?php echo $customerModel->getFirstName() ?>
                    </p>
                    <p><strong>Last Name:</strong>
                        <?php echo $customerModel->getLastName() ?>
                    </p>
                    <p><strong>Default:</strong>
                        <?php echo $customerModel->getDefault() ?>
                    </p>
                </div>
                <div class="customer-info mt-3">
                    <h4>Billing Address</h4>
                    <p><strong>Address:</strong>
                        <?php echo $customerModel->getBillingAddress() ?>
                    </p>
                    <p><strong>City:</strong>
                        <?php echo $customerModel->getBillingCity() ?>
                    </p>
                    <p><strong>Region:</strong>
                        <?php echo $customerModel->getBillingRegion() ?>
                    </p>
                    <p><strong>Country:</strong>
                        <?php echo $customerModel->getBillingCountry() ?>
                    </p>
                    <p><strong>Phone:</strong>
                        <?php echo $customerModel->getBillingPhone() ?>
                    </p>
                </div>
                <div class="customer-info mt-3">
                    <h4>Shipping Address</h4>
                    <p><strong>Address:</strong>
                        <?php echo $customerModel->getShippingAddress() ?>
                    </p>
                    <p><strong>City:</strong>
                        <?php echo $customerModel->getShippingCity() ?>
                    </p>
                    <p><strong>Region:</strong>
                        <?php echo $customerModel->getShippingRegion() ?>
                    </p>
                    <p><strong>Country:</strong>
                        <?php echo $customerModel->getShippingCountry() ?>
                    </p>
                    <p><strong>Phone:</strong>
                        <?php echo $customerModel->getShippingPhone() ?>
                    </p>
                </div>
                <div class="mt-3">
                    <a class="edit" href="register?pid=<?php echo $customerModel->getCustomerId() ?>">Edit</a>
                    <a class="delete" href="delete?pid=<?php echo $customerModel->getCustomerId() ?>">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>