<section class="list">
    <table class="table_body">
        <thead>
            <tr>
                <th>Customer Id</th>
                <th>Customer Email</th>
                <th>Customer Password</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Billing Address</th>
                <th>Billing City</th>
                <th>Billing Region</th>
                <th>Billing Country</th>
                <th>Billing Phone</th>
                <th>Shipping Address</th>
                <th>Shipping City</th>
                <th>Shipping Region</th>
                <th>Shipping Country</th>
                <th>Shipping Phone</th>
                <th>Default</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $customerModel = $this->getCustomer();
            ?>
            <tr>
                <td>
                    <?php echo $customerModel->getCustomerId() ?>
                </td>
                <td>
                    <?php echo $customerModel->getCustomerEmail() ?>
                </td>
                <td>
                    <?php echo $customerModel->getCustomerPassword() ?>
                </td>
                <td>
                    <?php echo $customerModel->getFirstName() ?>
                </td>
                <td>
                    <?php echo $customerModel->getLastName() ?>
                </td>
                <td>
                    <?php echo $customerModel->getBillingAddress() ?>
                </td>
                <td>
                    <?php echo $customerModel->getBillingCity() ?>
                </td>
                <td>
                    <?php echo $customerModel->getBillingRegion() ?>
                </td>
                <td>
                    <?php echo $customerModel->getBillingCountry() ?>
                </td>
                <td>
                    <?php echo $customerModel->getBillingPhone() ?>
                </td>
                <td>
                    <?php echo $customerModel->getShippingAddress() ?>
                </td>
                <td>
                    <?php echo $customerModel->getShippingCity() ?>
                </td>
                <td>
                    <?php echo $customerModel->getShippingRegion() ?>
                </td>
                <td>
                    <?php echo $customerModel->getShippingCountry() ?>
                </td>
                <td>
                    <?php echo $customerModel->getShippingPhone() ?>
                </td>
                <td>
                    <?php echo $customerModel->getDefault() ?>
                </td>
                <td>
                    <a href="register?pid=<?php echo $customerModel->getCustomerId() ?>" class="edit">Edit</a>
                </td>
                <td>
                    <a href="delete?pid=<?php echo $customerModel->getCustomerId() ?>" class="delete">Delete</a>
                </td>
            </tr>
        </tbody>
    </table>
</section>