<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <?php echo $this->getChildHtml('head'); ?>
</head>

<body>
    <form action="">
        <div class="header"></div>
        <?php echo $this->getChildHtml('header'); ?>
        <div class="content">
            <div class="left">Left</div>
            <div class="content">
                <?php echo $this->getChildHtml('content'); ?>
            </div>
            <div class="right">Right</div>
        </div>
        <div class="footer">
            <?php echo $this->getChildHtml('footer'); ?>
        </div>
    </form>
</body>

</html>