<?php

?>

<form action="save" method="post">

    <input type="text" hidden value="" name="cource[en_id]">
    <label for="Name"> Student Name : </label>
    <input type="text" name="cource[student_name]">
    <div class="dropdown">
        <button class="btn btn-success dropdown-toggle" type="button" id="multiSelectDropdown" data-bs-toggle="dropdown"
            aria-expanded="false">
            Chooce Cources
        </button>
        <ul class="dropdown-menu" aria-labelledby="multiSelectDropdown">
            <li>
                <label>
                    <input type="checkbox" value="PHP" name="cource[selected_cource][]">
                    PHP
                </label>
            </li>
            <li>
                <label>
                    <input type="checkbox" value="Javascript" name="cource[selected_cource][]">
                    Javascript
                </label>
            </li>
            <li>
                <label>
                    <input type="checkbox" value="JQuery" name="cource[selected_cource][]">
                    JQuery
                </label>
            </li>
            <li>
                <label>
                    <input type="checkbox" value="AJAX" name="cource[selected_cource][]">
                    AJAX
                </label>
            </li>
            <li>
                <label>
                    <input type="checkbox" value="MVC" name="cource[selected_cource][]">
                    MVC
                </label>
            </li>
            <li>
                <label>
                    <input type="checkbox" value="Magento1" name="cource[selected_cource][]">
                    Magento1
                </label>
            </li>
        </ul>
    </div>

    <div class="">
        <label for="term" class="heading">term :</label>
        <select name="cource[term]" id="categories">
            <option value="3">3 Months</option>
            <option value="6">6 Months</option>
            <option value="9">9 Months</option>
            <option value="12">12 Months</option>
            <option value="15">15 Months</option>
            <option value="18">18 Months</option>
            <option value="21">21 Months</option>
            <option value="24">24 Months</option>
        </select>
    </div>
    <input type="submit" value="Submit">

</form>