<?php
$cid = $this->getRequest()->getParams('cid', 0);
$categoryModel = Mage::getModel('catalog/product')->getCollection()
    ->addFieldToFilter('category_id', $cid);

?>
<div class="container">
    <div class="row">
        <?php $count = 0; ?>
        <?php foreach ($categoryModel->getData() as $categoryModel): ?>
            <div class="col-md-4 mb-4">
                <div class="card" style="background-color: #C7C8CC;">
                    <img class="card-img-top" style="height: 250px; object-fit: cover;"
                        src="<?php echo Mage::getBaseUrl() . 'media/product/' . $categoryModel->getImageLink() ?>"
                        alt="Product Image">
                    <div class="card-body">
                        <h5 class="card-title">
                            <?php echo $categoryModel->getName() ?>
                        </h5>
                        <p class="card-text">
                            <strong>Category:</strong>
                            <?php echo $categoryModel->getCategoryId() ?><br>
                            <strong>Price:</strong>
                            <?php echo $categoryModel->getPrice() ?><br>
                            <!-- Add more details as needed -->
                        </p>
                        <a href="<?php echo $this->getUrl('catalog/product/view?pid=' . $categoryModel->getId()) ?>"><button
                                class="btn btn-primary">View</button></a>
                    </div>
                </div>
            </div>

            <?php $count++; ?>
            <?php if ($count % 3 === 0): ?>
            </div>
            <div class="row">
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>