<footer class="bg-dark text-center text-lg-start text-white" style="background-color: #929fba">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
        <!-- Section: Links -->
        <section class="">
            <!--Grid row-->
            <div class="row">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h6 class="text-uppercase mb-4 font-weight-bold">
                        SHOP ME
                    </h6>
                    <p>
                        Be it clothing, footwear or accessories, ShopMe offers you the ideal combination of fashion and
                        functionality for men, women and kids.
                    </p>
                </div>
                <!-- Grid column -->

                <hr class="w-100 clearfix d-md-none" />

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                    <h6 class="text-uppercase mb-4 font-weight-bold">Features</h6>
                    <p>
                        <a class="text-white" href="#">Coupons</a>
                    </p>
                    <p>
                        <a class="text-white" href="#">Product Reviews</a>
                    </p>
                    <p>
                        <a class="text-white" href="#">What's New</a>
                    </p>
                    <p>
                        <a class="text-white" href="#">Help</a>
                    </p>
                </div>
                <!-- Grid column -->

                <hr class="w-100 clearfix d-md-none" />

                <!-- Grid column -->
                <hr class="w-100 clearfix d-md-none" />

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
                    <p><i class="fas fa-home mr-3"></i> CyberCom Creation AHMEDABAD, INDIA</p>
                    <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
                    <p><i class="fas fa-phone mr-3"></i> + 91 799 032 8923</p>
                    <p><i class="fas fa-print mr-3"></i> + 91 799 032 8923</p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                    <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>

                    <!-- Facebook -->
                    <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #FFCAD4"
                        href="https://www.facebook.com/" role="button">
                        <img src="<?php echo Mage::getBaseUrl() . "skin/images/facebook_logo.png" ?>" alt="">
                    </a>

                    <!-- Twitter -->
                    <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #55acee"
                        href="https://twitter.com/login" role="button"><img
                            src="<?php echo Mage::getBaseUrl() . "skin/images/twitter_logo.JPG" ?>" alt="">
                    </a>
                    <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #FEFBF6"
                        href="https://www.google.com/" role="button"><img
                            src="<?php echo Mage::getBaseUrl() . "skin/images/google.jpg" ?>" alt=""></a>

                    <!-- Instagram -->
                    <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #9AD0C2"
                        href="https://www.instagram.com/accounts/login/" role="button"><img
                            src="<?php echo Mage::getBaseUrl() . "skin/images/instagram_logo.PNG" ?>" alt="">

                        <!-- Linkedin -->
                        <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #B47B84"
                            href="https://www.linkedin.com/login" role="button"><img
                                src="<?php echo Mage::getBaseUrl() . "skin/images/linkedin.png" ?>" alt=""></a>
                        <!-- Github -->
                        <a class="btn btn-primary btn-floating m-1 logo" style="background-color: #000000"
                            href="https://github.com/login" role="button"><img
                                src="<?php echo Mage::getBaseUrl() . "skin/images/github.png" ?>" alt=""></a>
                </div>
            </div>
            <!--Grid row-->
        </section>
        <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2024 Copyright:
        <a class="text-white" href="http://localhost/practice/MVC_New/">shopme.com</a>
    </div>
    <!-- Copyright -->
</footer>