<footer class="bg-dark text-center text-lg-start text-white" style="background-color: #929fba">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
        <!-- Section: Links -->
        <section class="">
            <!--Grid row-->
            <div class="row">
                <!-- Grid column -->
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h6 class="text-uppercase mb-4 font-weight-bold">
                        SHOP ME
                    </h6>
                    <p>
                        Be it clothing, footwear or accessories, ShopMe offers you the ideal combination of fashion and
                        functionality for men, women and kids.
                    </p>
                </div>
                <!-- Grid column -->

                <hr class="w-100 clearfix d-md-none" />

                <!-- Grid column -->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
                    <h6 class="text-uppercase mb-4 font-weight-bold">Features</h6>
                    <p>
                        <a class="text-white" href="#">Coupons</a>
                    </p>
                    <p>
                        <a class="text-white" href="#">Product Reviews</a>
                    </p>
                    <p>
                        <a class="text-white" href="#">What's New</a>
                    </p>
                    <p>
                        <a class="text-white" href="#">Help</a>
                    </p>
                </div>
                <!-- Grid column -->

                <hr class="w-100 clearfix d-md-none" />

                <!-- Grid column -->
                <hr class="w-100 clearfix d-md-none" />

                <!-- Grid column -->
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
                    <p><i class="fas fa-home mr-3"></i> CyberCom Creation AHMEDABAD, INDIA</p>
                    <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
                    <p><i class="fas fa-phone mr-3"></i> + 91 799 032 8923</p>
                    <p><i class="fas fa-print mr-3"></i> + 91 799 032 8923</p>
                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
                    <h6 class="text-uppercase mb-4 font-weight-bold">Follow us</h6>

                    <!-- Social media icons -->
                    <div class="d-flex justify-content-between">
                        <!-- Facebook -->
                        <a href="https://www.facebook.com/" style="color:white"><i
                                class="fa-brands fa-facebook me-3"></i></a>
                        <!-- Twitter -->
                        <a href="https://twitter.com/login" style="color:white"><i
                                class="fa-brands fa-x-twitter me-3"></i></a>
                        <!-- Instagram -->
                        <a href="https://www.instagram.com/accounts/login/" style="color:white"><i
                                class="fa-brands fa-instagram me-3"></i></a>
                        <!-- Linkedin -->
                        <a href="https://www.linkedin.com/login" style="color:white"><i
                                class="fa-brands fa-linkedin"></i></a>
                    </div>

                    <!-- Contact Us -->
                    <div class="mt-3">
                        <h5>Contact Us</h5>
                        <form method="post" action="<?php echo $this->getUrl('contactus/message/save') ?>">
                            <div class="form-group">
                                <input type="email" class="form-control" placeholder="Your email address"
                                    name="msg[email_id]">
                            </div>
                            <div class="form-group mt-1">
                                <textarea class="form-control" rows="3" placeholder="Your message"
                                    name="msg[message]"></textarea>
                            </div>
                            <button type="submit" class="btn btn-success btn-block mb-3 mt-1"
                                onclick='return alertmsg()'>Send</button>
                        </form>
                    </div>
                </div>
            </div>
            <!--Grid row-->
        </section>
        <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2024 Copyright:
        <a class="text-white" href="http://localhost/practice/MVC_New/">shopme.com</a>
    </div>
    <!-- Copyright -->
</footer>

<script>
    function alertmsg() {
        alert('Thank you for contacting us.We will get back to you soon.');
        return true;
    }
</script>