<!-- <h1>Head</h1> -->

<?php $js = $this->getJs(); ?>

<?php if (count($js) > 0): ?>
    <?php foreach ($js as $_js): ?>
        <?php echo $_js . "<br>" ?>
        <script type="" src="<?php echo $_js; ?>"></script>
    <?php endforeach ?>
<?php endif ?>

<?php $css = $this->getCss(); ?>

<?php if (count($css) > 0): ?>
    <?php foreach ($css as $_css): ?>
        <?php echo $_css . "<br>" ?>
        <link rel="stylesheet" href="<?php echo $_css ?>">
    <?php endforeach ?>
<?php endif ?>