<?php
$categories = Mage::getModel('catalog/category')->getCollection();
?>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark pb-2 pt-2">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><i class="fa-brands fa-slack m-2"></i><span
                style="color: #F6F193;">S</span>hop<span style="color: #e44d26;">M</span>e</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto"> <!-- Use ms-auto here -->
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="<?php echo $this->getUrl("") ?>">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?php echo $this->getUrl("catalog/product/view") ?>">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Pricing</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Options
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="<?php echo $this->getUrl("customer/account/dashboard") ?>">My
                                Account</a></li>
                        <li><a class="dropdown-item" href="<?php echo $this->getUrl("sales/quote/view") ?>">Cart</a>
                        </li>
                        <li><a class="dropdown-item" href="<?php echo $this->getUrl("sales/order/list") ?>">My
                                Orders</a></li>
                        <li><a class="dropdown-item"
                                href="<?php echo $this->getUrl("customer/account/register") ?>">Sign In</a>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2 mt-1" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light me-2 mt-2" type="submit">Search</button>
                <a href="<?php echo $this->getUrl("customer/account/login") ?>"><button type="button"
                        class="btn btn-outline-light me-2 mt-2">Login</button></a>
                <a href="<?php echo $this->getUrl("customer/account/logout") ?>"><button type="button"
                        class="btn btn-outline-light me-2 mt-2">Logout</button></a>
            </form>
        </div>
    </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav d-flex justify-content-between w-100">
            <!-- Category links -->
            <?php foreach ($categories->getData() as $category) { ?>
                <a class="nav-item nav-link"
                    href="<?php echo $this->getUrl("catalog/category/view?cid=" . $category->getId()) ?>">
                    <?php echo $category->getCategoryName(); ?>
                </a>
            <?php } ?>
        </div>
    </div>
</nav>