<section class="list">
    <table class="table_body">
        <thead>
            <tr>
                <th>Product Id</th>
                <th>Product Name</th>
                <th>SKU</th>
                <th>Color</th>
                <th>Size</th>
                <th>Description</th>
                <th>Image Link</th>
                <th>Link</th>
                <th>Category</th>
                <th>Price</th>
                <th>Status</th>
                <th>View</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $productCollection = Mage::getModel("catalog/product")->getCollection();
            //->addFieldToFilter('price', ['gt' => 3]);
            // ->addFieldToFilter('name', ['not' => 'book'])
            // ->addFieldToGroupBy('name,price')
            // ->addFieldToOrderBy('product_id', 'DESC')
            // ->limit(3);
            
            foreach ($productCollection->getData() as $product):

                ?>
                <tr>
                    <td>
                        <?php echo $product->getId() ?>
                    </td>
                    <td>
                        <?php echo $product->getName() ?>
                    </td>
                    <td>
                        <?php echo $product->getSku() ?>
                    </td>
                    <td>
                        <?php echo $product->getColor() ?>
                    </td>
                    <td>
                        <?php echo $product->getSize() ?>
                    </td>
                    <td>
                        <?php echo $product->getDescription() ?>
                    </td>
                    <td>
                        <img style="height:60px; width:100px; border-radius: 20%;"
                            src="<?php echo Mage::getBaseUrl() . 'media/product/' . $product->getImageLink() ?>" alt="">
                    </td>
                    <td>
                        <?php echo $product->getLink() ?>
                    </td>
                    <td>
                        <?php echo $product->getCategoryId() ?>
                    </td>
                    <td><strong>
                            <?php echo $product->getPrice() ?>
                        </strong>
                    </td>
                    <td>
                        <?php echo $product->getStatus() ?>
                    </td>
                    <td>
                        <a href="view?pid=<?php echo $product->getId() ?>" class="edit">View</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>