<?php
$productCollection = Mage::getModel("catalog/product")->getCollection();
//->addFieldToFilter('price', ['gt' => 3]);
// ->addFieldToFilter('name', ['not' => 'book'])
// ->addFieldToGroupBy('name,price')
// ->addFieldToOrderBy('product_id', 'DESC')
// ->limit(3);
$products = $productCollection->getData();

?>

<div class="container">
    <div class="row">
        <?php $count = 0; ?>
        <?php foreach ($products as $product): ?>
            <div class="col-md-4 mb-4">
                <div class="card" style="background-color: #C7C8CC;">
                    <img class="card-img-top" style="height: 250px; object-fit: cover;"
                        src="<?php echo Mage::getBaseUrl() . 'media/product/' . $product->getImageLink() ?>"
                        alt="Product Image">
                    <div class="card-body">
                        <h5 class="card-title">
                            <?php echo $product->getName() ?>
                        </h5>
                        <p class="card-text">
                            <strong>Category:</strong>
                            <?php echo $product->getCategoryId() ?><br>
                            <strong>Price:</strong>
                            <?php echo $product->getPrice() ?><br>
                            <!-- Add more details as needed -->
                        </p>
                        <a href="view?pid=<?php echo $product->getId() ?>" class="btn btn-primary">View</a>
                    </div>
                </div>
            </div>

            <?php $count++; ?>
            <?php if ($count % 3 === 0): ?>
            </div>
            <div class="row">
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>