<?php
$catalogModel = $this->getProductDetail();
?>
<div class="container" style="margin : 50px; margin-left : 100px;">
    <div class="row">
        <div class="col-md-12 mb-4">
            <div class="card" style="background-color: #C7C8CC;">
                <div class="row">
                    <div class="col-md-6">
                        <img class="card-img-top" style="height: 500px;"
                            src="<?php echo Mage::getBaseUrl() . 'media/product/' . $catalogModel->getImageLink() ?>"
                            alt="Product Image">
                    </div>
                    <div class="col-md-6" style="padding-top : 90px;">
                        <div class="card-body">
                            <h3 class="card-title">
                                <?php echo $catalogModel->getName() ?>
                            </h3>
                            <h6 class="card-text">
                                <strong>Category:</strong>
                                <?php echo $catalogModel->getCategoryId() ?><br>
                            </h6>
                            <h6>
                                <strong>Description:</strong>
                                <?php echo $catalogModel->getDescription() ?><br>
                            </h6>
                            <h6>
                                <strong>Price:</strong>
                                <?php echo $catalogModel->getPrice() ?><br>
                            </h6>
                            <h6>
                                <strong>Color:</strong>
                                <?php echo $catalogModel->getColor() ?><br>
                            </h6>
                            <h6>
                                <strong>Size:</strong>
                                <?php echo $catalogModel->getSize() ?><br>
                            </h6>
                            <h6>
                                <!-- Add more details as needed -->
                                <div class="mt-3">
                                    <form action="<?php echo $this->getUrl('sales/quote/add') ?>" method="post">
                                        <input type="text" hidden name="cart[product_id]"
                                            value="<?php echo $catalogModel->getId() ?>">
                                        <input type="text" hidden name="cart[Product_name]"
                                            value="<?php echo $catalogModel->getName() ?>">
                                        <label for="">Quantity : </label>
                                        <input type="number" name="cart[qty]" min="1"
                                            max="<?php echo $catalogModel->getInventory() ?>" value="1">
                                        <?php
                                        if ($catalogModel->getInventory() > 0) { ?>
                                            <button class="buttton" type="submit" name="submit">Add To Cart</button>
                                            <?php
                                        } else {
                                            ?>
                                            <h3 style="color:#A0153E" class="mt-3">Out of Stock !!</h3>
                                            <?php
                                        }
                                        ?>
                                    </form>
                                </div>
                            </h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>