<div class="container-fluid">
    <div class="row">
        <!-- Sidebar -->
        <nav class="col-md-3 col-lg-2 d-md-block bg-dark sidebar">
            <div class="sidebar-sticky">
                <h2 class="sidebar-heading">Dashboard</h2>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link dash" href="#">My Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="#">My Wallet</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="#">My Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="#">Wishlist</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="#">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link dash" href="#">My Cart</a>
                    </li>
                </ul>
            </div>
        </nav>
        <?php
        $catalogModel = $this->getProductDetail();
        ?>
        <div class="col-md-9 col-lg-10 px-md-4 list">
            <div class="customer-details">
                <h2>Product Details</h2>
                <div class="customer-info">
                    <h4>Product Information</h4>
                    <div style="display: flex; align-items: center;">
                        <p style="flex: 1;"><strong>Product Name: </strong>
                            <?php echo $catalogModel->getName() ?>
                        </p>
                        <img style="height: 100px; width: 150px; border-radius: 20%;"
                            src="<?php echo Mage::getBaseUrl() . 'media/banner/' . $catalogModel->getImageLink() ?>"
                            alt="">
                    </div>
                    <p><strong>Product SKU: </strong>
                        <?php echo $catalogModel->getSku() ?>
                    </p>
                    <p><strong>Product Color: </strong>
                        <?php echo $catalogModel->getColor() ?>
                    </p>
                    <p><strong>Product Size: </strong>
                        <?php echo $catalogModel->getSize() ?>
                    </p>
                </div>
                <div class="customer-info mt-3">
                    <h4>Description And Image</h4>
                    <p><strong>Description: </strong>
                        <?php echo $catalogModel->getDescription() ?>
                    </p>
                    <p><strong>Image Link: </strong>
                        <?php echo $catalogModel->getImageLink() ?>
                    </p>
                    <p><strong>Link: </strong>
                        <?php echo $catalogModel->getLink() ?>
                    </p>
                </div>
                <div class="customer-info mt-3">
                    <h4>Category and Price</h4>
                    <p><strong>Category: </strong>
                        <?php echo $catalogModel->getCategoryId() ?>
                    </p>
                    <p><strong>Status:</strong>
                        <?php echo $catalogModel->getStatus() ?>
                    </p>
                    <p><strong>Price:
                            <?php echo $catalogModel->getPrice() ?>
                        </strong>
                    </p>
                </div>
                <div class="mt-3">
                    <form action="<?php echo $this->getUrl('sales/quote/add') ?>" method="post">
                        <input type="text" hidden name="cart[id]" value="<?php echo $catalogModel->getId() ?>">
                        <input type="text" hidden name="cart[name]" value="<?php echo $catalogModel->getName() ?>">
                        <label for="">Quantity : </label>
                        <input type="number" name="cart[quantity]">
                        <button class="buttton" type="submit" name="submit">Add To Cart</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>