<?php
$category = $this->getCategory();
?>

<section class="formlist">
    <form action="<?php echo $this->getUrl("admin/catalog_category/save") ?>" method="post" class="form"
        onsubmit="return validateForm()">
        <div class="center">
            <h1>Category Form</h1>
            <div class="form-group row">
                <input hidden type="text" placeholder="Enter your product name" name="cat_data[category_id]" id=""
                    value="">
            </div>
            <br>
            <div class="form-group row">
                <label for="">Category Name : </label>
                <input type="text" placeholder="Enter category name" name="cat_data[category_name]" id="category_name"
                    value="<?php echo $category->getCategoryName(); ?>">
                <span id="category_name_error" style="color: red;"></span>
            </div>
            <br>
            <div class="form-group row">
                <label for="">Status : </label>
                <input type="text" placeholder="Enter Status" name="cat_data[status]" id=""
                    value="<?php echo $category->getStatus(); ?>">
            </div>
            <button class="buttton" type="submit" name="submit">Submit</button>
        </div>
    </form>
</section>

<script>
    function validateForm() {
        var categoryName = document.getElementById("category_name").value;
        var categoryNameError = document.getElementById("category_name_error");

        if (!/^[a-zA-Z]+$/.test(categoryName)) {
            categoryNameError.innerText = "Category name should contain only alphabets";
            return false;
        } else {
            categoryNameError.innerText = "";
            return true;
        }
    }
</script>