<section class="formlist">
    <form action="" id="login-form" method="post" class="form">
        <div class="center">
            <h1 class="mb-4">Log In</h1>
            <div class="form-group row">
                <label for="">Email : </label>
                <input type="text" placeholder="Enter your email " name="c_login[customer_email]" id="" value="">
            </div>
            <br>
            <div class="form-group row">
                <label for="">Password : </label>
                <input type="password" placeholder="Enter your password" name="c_login[customer_password]" id=""
                    value="">
            </div>
            <div class="form-group row">
                <a href="<?php Mage::getBaseUrl() . 'customer/account/forgot'; ?>" class="forgot">Password not Remember
                    ?</a>
            </div>
            <button class="buttton" type="button" onclick="loginAction(this)" name="submit">Log In</button>
            <div id="message"></div>
        </div>
    </form>
</section>

<script type="text/javascript">
    function loginAction(btn) {
        //console.log($('#login-form'));
        var form = $($('#login-form')[0]);
        console.log(form.serialize());
        $.ajax({
            url: form.action,
            type: 'POST',
            // contentType: "application/json",
            data: form.serialize()
        }).done(function (response) {
            var output = JSON.parse(response);
            // alert(response)
            alert(output.type)
            $('#message')[0].innerHTML = output.message;
            // alert(output.message)
            if (output.type == "success") {
                alert(output.message);
                // window.location.href = "<?php echo $this->getUrl('customer/account/dashboard'); ?>";
            }
            else {
                alert(output.message);
            }
            // $('#message')[0].innerHTML = output.message;
            // alert(output.message)
            // $( this ).addClass( "done" );
            // $( this ).addClass( "done" );
        });
    }
</script>