<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #265073;">
    <a class="navbar-brand" href="<?php echo $this->getUrl("admin/account/login") ?>" style="color: #fff;"><i
            class="fa-solid fa-user-shield m-2"></i>Admin Panel</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNav">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->getUrl('admin/account/dashboard') ?>"
                    style="color: #fff;">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->getUrl('admin/customer/list') ?>"
                    style="color: #fff;">Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->getUrl("admin/orders/view") ?>"
                    style="color: #fff;">Orders</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false" style="color: #fff;">
                    Products
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="<?php echo $this->getUrl("admin/catalog_product/form") ?>">
                            Add Produts</a></li>
                    <li><a class="dropdown-item"
                            href="<?php echo $this->getUrl("admin/catalog_product/list") ?>">Products
                            List</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false" style="color: #fff;">
                    Category
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="<?php echo $this->getUrl("admin/catalog_category/form") ?>">Add
                            Category</a></li>
                    <li><a class="dropdown-item"
                            href="<?php echo $this->getUrl("admin/catalog_product/list") ?>">Category
                            List</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false" style="color: #fff;">
                    Banner
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="<?php echo $this->getUrl("admin/banner/form") ?>">Add
                            Banner</a></li>
                    <li><a class="dropdown-item" href="<?php echo $this->getUrl("admin/banner/list") ?>">Banner
                            List</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="<?php echo $this->getUrl("admin/account/logout") ?>"
                    style="color: #fff;">Logout</a>
            </li>

            <!-- Add more navigation items as needed -->
        </ul>
    </div>
</nav>