<h2 class="center m-5">Upload-Import CSV</h2>
<form action="<?php echo $this->getUrl("admin/import/upload") ?>" method="post" class="form"
    enctype="multipart/form-data">
    <div class="form-group row">
        <label for="">Upload a CSV file : </label>
        <input type="file" name="importfile" id="" value="">
    </div>
    <button class="buttton" type="submit" name="submit">Upload File</button>
    <button class="buttton" type="submit" formaction="<?php echo $this->getUrl("admin/import/read") ?>">Read</button>
</form>