<section class="formlist">
    <form action="" method="post" class="form">
        <div class="center">
            <h1 class="mb-4">Admin Log In</h1>
            <div class="form-group row">
                <label for="">UserName : </label>
                <input type="text" placeholder="Enter your username or email " name="a_login[admin_username]" id=""
                    value="">
            </div>
            <br>
            <div class="form-group row">
                <label for="">Password : </label>
                <input type="password" placeholder="Enter your password" name="a_login[admin_password]" id="" value="">
            </div>
            <button class="buttton" type="submit" name="submit">Log In</button>
        </div>
    </form>
</section>